# Site settings
title: Bob's Coding Lab
SEOTitle: 鸽鱼的编程实验室 | Bob's Coding Lab
header-img: img/post-bg-desk.jpg
email: boblao0714@gmail.com
description: "业精于勤荒于嬉，Keep Coding，Keep Improving"
keyword: "Bob，Bob Guo，Bob's Coding Lab，鸽鱼, PegionFish"
url: "https://pegionfish.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/PegionFish/PegionFish.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "动画 V曲 游戏 ラノベ カゲプロ最高た　格里芬指挥官 FPS玩家 UP主 金🐦🐦的电波曲真好听"
sidebar-avatar: /img/隔雨听竹2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
zhihu_username:     ge-yu-ting-zhu-82
github_username:    PegionFish





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4794b781b3c300b9ca7c                            #生成的clientID
  clientSecret: 55ee2becf199077a4a308415b5376d18b553066a    #生成的clientSecret
  repo: pegionfish.github.io    #仓库名称
  owner: PegionFish    #github用户名
  admin: PegionFish
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings

# Google Analytics
ga_track_id: 'UA-136382680-1'            # Format: UA-xxxxxx-xx
ga_domain: auto             # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "E哥",
        href: "https://edward40.com/"
    },
    {
        title: "Main包",
        href: "https://himself65.com/"
    },
    {
        title: "OC",
        href: "https://originco.de/"
    },
    {
        title: "moi某",
        href: "https://rain.moimo.me/"
    },
    {
        title: "小雪",
        href: "https://qiancy98.github.io/"
    }
    {
        title: "鱼塔老师" ,
        href: "https://blog.yuuta.moe/"
    }
]